// [문제 링크]: https://school.programmers.co.kr/learn/courses/30/lessons/133026

-- 코드를 입력하세요
SELECT A.INGREDIENT_TYPE, SUM(A.TOTAL_ORDER) AS TOTAL_ORDER FROM 
(SELECT C.INGREDIENT_TYPE, B.TOTAL_ORDER FROM FIRST_HALF AS B 
 LEFT JOIN ICECREAM_INFO AS C
 ON B.FLAVOR = C.FLAVOR) 
 AS A
GROUP BY INGREDIENT_TYPE