// [문제 링크]: https://school.programmers.co.kr/learn/courses/30/lessons/133027

-- 코드를 입력하세요
SELECT FLAVOR FROM (
SELECT FLAVOR, (TOTAL_ORDER+TO_J) AS SUMS FROM(
SELECT A.FLAVOR, A.TOTAL_ORDER, B.FLAVOR AS FL_J, B.TO_J FROM FIRST_HALF A LEFT JOIN ( 
SELECT SHIPMENT_ID, FLAVOR, SUM(TOTAL_ORDER) AS TO_J FROM JULY
GROUP BY FLAVOR) B
ON A.SHIPMENT_ID = B.SHIPMENT_ID) C
ORDER BY SUMS DESC) AS D
LIMIT 3;