// [문제 링크]: https://school.programmers.co.kr/learn/courses/30/lessons/131117

-- 코드를 입력하세요
SELECT A.PRODUCT_ID, A.PRODUCT_NAME, (A.PRICE * SUMS) AS TOTAL_SALES FROM
FOOD_PRODUCT A JOIN 
(SELECT PRODUCT_ID, SUM(AMOUNT) AS SUMS 
 FROM FOOD_ORDER 
 WHERE MONTH(PRODUCE_DATE) = 5 
 GROUP BY PRODUCT_ID) B
ON A.PRODUCT_ID = B.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID ASC;


# SELECT PRODUCT_ID, SUM(AMOUNT)
#  FROM FOOD_ORDER 
#  WHERE MONTH(IN_DATE) = 5 
#  GROUP BY PRODUCT_ID
# SELECT * FROM FOOD_PRODUCT;