// [문제 링크]: https://school.programmers.co.kr/learn/courses/30/lessons/59412

-- 코드를 입력하세요
SELECT HOUR(DATETIME) AS HOUR, COUNT(ANIMAL_ID) AS COUNT 
FROM ANIMAL_OUTS 
WHERE HOUR(DATETIME) BETWEEN 9 AND 19
GROUP BY HOUR(DATETIME) 
ORDER BY HOUR(DATETIME)