// [문제 링크]: https://school.programmers.co.kr/learn/courses/30/lessons/164668

-- 코드를 입력하세요
SELECT USER_ID, NICKNAME, SUM(PRICE) AS TOTAL_SALES
FROM (SELECT * FROM USED_GOODS_BOARD WHERE STATUS = 'DONE') A 
LEFT JOIN USED_GOODS_USER B ON A.WRITER_ID = B.USER_ID
GROUP BY A.WRITER_ID
HAVING TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES ASC;